In [1]:
from pathlib import Path
import pgm2pil

fname = 'datasets/faces/an2i/an2i_left_neutral_open_4.pgm'
an2i = Path( fname )
an2i.exists()

import PIL.Image
#origImageOpen = PIL.Image.open
#PIL.Image.open = pgm2pil.imageOpenWrapper
an2i_im = PIL.Image.open(fname)
print(an2i_im)

# or we can use the misc package that in turn uses PIL
from scipy import misc
an2i_im = misc.imread(fname)

import importlib
# importlib.reload(pgm2pil)


# not needed anymore changed pgm2pil
# import numpy as np
# an2i_im_up = np.flipud(an2i_im)

import matplotlib.pyplot as plt

# make it non-blocking -- only needed once
plt.ion() 

plt.imshow(an2i_im, cmap=plt.cm.gray)
# Only needed if blocking
#plt.show()

<PIL.PpmImagePlugin.PpmImageFile image mode=L size=32x30 at 0x160BA02CB00>


C:\Users\Sophie\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  app.launch_new_instance()


In [2]:
print(len(an2i_im))
print(len(an2i_im[0]))
print(an2i_im)

30
32
[[ 45  19  25  58  45  52  45  44  42  40  38  36  34  32  29  27  26  27
   29  24  27  25  24  27  28  29  30  32  33  35  36  38]
 [ 42   6   5  47   3  23  47  44  43  42  40  38  36  34  33  30  29  30
   32  27  30  28  26  31  32  32  33  34  36  37  38  39]
 [ 47  18  14  44   5  21  46  44  43  41  40  38  37  35  33  31  30  31
   33  29  32  29  28  32  33  34  34  35  36  38  39  40]
 [ 26  24  28  32  28  37  45  44  42  41  40  39  37  35  34  31  30  30
   34  29  30  30  29  33  34  35  35  36  38  39  40  40]
 [ 29  29  34  46  34  29  25  26  38  42  40  37  34  32  27  19  19  16
   19  20  26  28  30  35  36  36  37  37  38  39  39  40]
 [ 13  20  15  41  26  40  51  43  37  45  46  20   3   6   2   0   0   0
    0   0   3  12  25  34  37  37  37  39  39  39  39  40]
 [  2  23  14  37   2  21  13  27  23  35   5   2   0   0   0   0   0   0
    0   0   0   0  11  31  36  39  39  39  40  40  40  41]
 [  2  40  28  37   7  16   6  17   8   5   1   0   0   0   0  

In [13]:
import numpy as np

# test append
a = np.array([[1, 2], [3, 4]])
print(a)
a = a.reshape(1, -1)
print(a)
#a = np.empty((1,1))
a = None

for i in range(10):
    #a = np.append(a, np.array([i]))
    if a is None:
        a = np.array([[i]])
    else:
        a = np.r_[a, np.array([[i]])]
    
print(a)

[[1 2]
 [3 4]]
[[1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
